name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "xugou-db"
database_id = "982e4ffd-e548-408e-b443-c700c5ccbf1a"

[version_metadata]
binding = "CF_VERSION_METADATA"
